name:                Kospi200
version:             0.1.0.0
license:             BSD3
author:              "Sophia Gold"
maintainer:          "sophiagoldnyc@gmail.com"
copyright:           "2018 Sophia Gold"

extra-source-files:
- README.md

description: Code Sample for Tsuru Capital

dependencies:
- base >= 4.9 && < 5
- async-timer
- attoparsec
- bytestring
- containers
- pcap
- text-show
- text-show-instances
- time

library:
  source-dirs:
  - src/  

executables:
  parse-quote:
    main:                ParseQuote.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - Kospi200

tests:
  parse-quote-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - Kospi200
    - tasty
    - tasty-hunit

benchmarks:
  parse-quote-bench:
    main:                Bench.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    - -with-rtsopts=-IO
    - -with-rtsopts=-A8G
    - -O2
    dependencies:
    - Kospi200
    - criterion
    - text
