resolver: lts-9.21

nix: {
  enable: true
  , packages: [libpcap
             , libcxx
             , icu
             , gcc
             , ncurses]
  }

extra-deps:
  - pcap-0.4.5.2
  
system-ghc: true
